language: php

sudo: false

git:
    depth: 1

cache:
  directories:
    - $HOME/.composer/cache

php:
    - '7.2'
    - '7.3'
    - '7.4'
    - '8.0'

env:
    - SYMFONY_VERSION=^3.0
    - SYMFONY_VERSION=^4.0
    - SYMFONY_VERSION=^5.0
    - SYMFONY_VERSION=^3.0  DEPS=low
    - SYMFONY_VERSION=^4.0  DEPS=low
    - SYMFONY_VERSION=^5.0  DEPS=low

before_script:
    - if [ "$DEPS" = 'low' ] ; then COMPOSER_PARAMS="--prefer-lowest --prefer-stable" ;  fi
    - composer self-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer update $COMPOSER_PARAMS

script:
    - ./vendor/bin/phpunit --coverage-text
    - ./vendor/bin/phpcs
